name: L2-tal
channels:
  - conda-forge
  - defaults
dependencies:
  - chardet
  - jupyterlab
  - jupyterlab-latex
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pip
  - python
  - seaborn
  - spacy
