name: L2-tal
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4
  - jupyterlab-latex=3.1
  - matplotlib=3.5
  - numpy=1.23
  - pandas=1.4
  - pip
  - python=3.10
  - seaborn=0.11
  - tabulate=0.9.0
