[project]
name = "L2TAL"
version = "0.1.1"
description = "Resources for L2TAL at Inalco"
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Alex-bzh/L2TAL"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = "~=4.1"
jupyterlab-latex = "~=3.0"
matplotlib = "~=3.0"
numpy = ">1.25"
pandas = ">2.0"
pip = ">23.3.0"
python = ">3.10"
seaborn = ">0.13.0"