[project]
name = "L2TAL"
version = "0.1.1"
description = "Resources for L2TAL at Inalco"
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Alex-bzh/L2TAL"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
chardet = "~=5.*"
jupyterlab = "~=4.*"
jupyterlab-latex = "~=3.*"
matplotlib = "~=3.*"
nltk = "~=3.*"
numpy = ">1.*"
pandas = ">2.*"
pip = ">23.*"
python = ">3.10"
seaborn = "~=0.*"
spacy = "~=3.*"
