[project]
name = "TALB230B"
version = "0.1.2"
description = "Resources for L2TAL at Inalco"
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Alex-bzh/L2TAL"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
jieba = "0.42.*"
jupyterlab = "4.3.*"
jupyterlab-latex = "4.*"
pip = ">=23"
python = ">=3.10.6"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
